services:
  customer-web:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_TELEGRAM_BOT_USERNAME: ${NEXT_PUBLIC_TELEGRAM_BOT_USERNAME}
    ports:
      - "3000:3000"
    env_file: .env
